name: Trivy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Enables manual triggering

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: write  # Required to commit updated README
      security-events: write  # Allows uploading SARIF results to GitHub Security tab
      actions: read  # Required for private repositories
      
    name: Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/notyusheng/open-webui_secure:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Extract scan results
        run: |
          # Get timestamps in UTC with Day Month Year format
          TIMESTAMP_UTC=$(date -u +"%d %b %Y %I:%M:%S %p UTC")

          # Convert to Singapore Time (SGT, UTC+8) in the same format
          TIMESTAMP_SGT=$(TZ=Asia/Singapore date +"%d %b %Y %I:%M:%S %p SGT")

          # Extract vulnerability counts
          CRITICAL=$(jq '[.Results[].Vulnerabilities? // [] | .[] | select(.Severity=="CRITICAL")] | length' trivy-results.sarif)
          HIGH=$(jq '[.Results[].Vulnerabilities? // [] | .[] | select(.Severity=="HIGH")] | length' trivy-results.sarif)

          # Store environment variables
          echo "LAST_SCAN_UTC=${TIMESTAMP_UTC}" >> $GITHUB_ENV
          echo "LAST_SCAN_SGT=${TIMESTAMP_SGT}" >> $GITHUB_ENV
          echo "CRITICAL_COUNT=${CRITICAL}" >> $GITHUB_ENV
          echo "HIGH_COUNT=${HIGH}" >> $GITHUB_ENV

      - name: Update README with scan results
        run: |
          # Define the placeholders
          START_PLACEHOLDER="<!-- TRIVY_SCAN_RESULTS -->"
          END_PLACEHOLDER="<!-- TRIVY_SCAN_END -->"

          # Generate the new scan results content
          SCAN_RESULTS="$START_PLACEHOLDER\n"
          SCAN_RESULTS+="## Latest Security Scan Results\n\n"
          SCAN_RESULTS+="🕒 **Last Scan (UTC):** $LAST_SCAN_UTC  \n"
          SCAN_RESULTS+="🕒 **Last Scan (SGT):** $LAST_SCAN_SGT  \n"
          SCAN_RESULTS+="🚨 **Critical Vulnerabilities:** $CRITICAL_COUNT  \n"
          SCAN_RESULTS+="⚠️ **High Vulnerabilities:** $HIGH_COUNT  \n"
          SCAN_RESULTS+="$END_PLACEHOLDER"

          # Use awk to replace only content between the placeholders
          awk -v start="$START_PLACEHOLDER" -v end="$END_PLACEHOLDER" -v new_content="$SCAN_RESULTS" '
            $0 == start {print new_content; inside=1; next}
            $0 == end {inside=0; next}
            !inside {print}
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update latest Trivy scan results in README"
          git push
