name: Trivy Security Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write  # Allows updating README file

jobs:
  scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        continue-on-error: true  # Continue workflow even if vulnerabilities exist
        run: |
          trivy image ghcr.io/notyusheng/open-webui_secure:latest \
            --severity HIGH,CRITICAL \
            --format table > trivy-results.txt
          echo "Trivy scan completed with exit code: $?"

      - name: Determine CVE Status
        run: |
          if [ ${{ steps.trivy_scan.outcome }} == "success" ]; then
            echo "SCAN_STATUS=✅ No High or Critical CVEs detected as of $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_ENV
          else
            echo "SCAN_STATUS=⚠️ Vulnerabilities detected! Review the security tab." >> $GITHUB_ENV
          fi

      - name: Update README with Scan Status
        run: |
          git pull --rebase  # Pull latest changes to avoid conflicts
          sed -i '/<!-- CVE-STATUS -->/c\<!-- CVE-STATUS -->\n${{ env.SCAN_STATUS }}' README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Trivy scan status in README" || echo "No changes to commit"
          git push
