name: Trivy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: write  # Required to commit updated README
      security-events: write  # Allows uploading SARIF results to GitHub Security tab
      actions: read  # Required for private repositories
      
    name: Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/notyusheng/open-webui_secure:latest'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'

      - name: Extract scan results
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          CRITICAL=$(jq '[.Results[].Vulnerabilities? // [] | .[] | select(.Severity=="CRITICAL")] | length' trivy-results.json)
          HIGH=$(jq '[.Results[].Vulnerabilities? // [] | .[] | select(.Severity=="HIGH")] | length' trivy-results.json)
          echo "LAST_SCAN=${TIMESTAMP}" >> $GITHUB_ENV
          echo "CRITICAL_COUNT=${CRITICAL}" >> $GITHUB_ENV
          echo "HIGH_COUNT=${HIGH}" >> $GITHUB_ENV

      - name: Update README with scan results
        run: |
          # Define the placeholder comment
          PLACEHOLDER="<!-- TRIVY_SCAN_RESULTS -->"

          # Generate the new scan results content with emojis
          SCAN_RESULTS="$PLACEHOLDER\n"
          SCAN_RESULTS+="## 🔍 Latest Security Scan Results\n\n"
          SCAN_RESULTS+="🕒 **Last Scan:** $LAST_SCAN  \n"
          SCAN_RESULTS+="🚨 **Critical Vulnerabilities:** $CRITICAL_COUNT  \n"
          SCAN_RESULTS+="⚠️ **High Vulnerabilities:** $HIGH_COUNT  \n"

          # Replace only the previous scan results while keeping the rest of the README intact
          awk -v placeholder="$PLACEHOLDER" -v content="$SCAN_RESULTS" '
            BEGIN { replaced=0 }
            $0 == placeholder { print content; replaced=1; next }
            replaced && /^## / { replaced=0 } # Stop replacing at the next section header
            !replaced { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update latest Trivy scan results in README"
          git push
