name: Trivy Security Scan

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  scan:
    name: Scan GHCR Image for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Trivy Scan and Save Report
        run: |
          mkdir -p reports  # Ensure the directory exists
          trivy image ghcr.io/notyusheng/open-webui_secure:latest \
            --severity HIGH,CRITICAL \
            --format table \
            --output reports/trivy-report.txt

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: reports/trivy-report.txt
