name: ZAP Full Scan on Docker Compose App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap-fullscan:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start Docker Compose App
        run: |
          docker-compose -f docker-compose.secure.yml up -d
          echo "Waiting for services..."
          sleep 20

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080'
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap_scan
          cmd_options: '-a -j'

      - name: Move ZAP reports to /reports folder
        run: |
          mkdir -p reports
          find reports/ ! -name '.gitkeep' -type f -delete
          find reports/ ! -name '.gitkeep' -type d -empty -delete

          if [ -d zap_scan ]; then
            cp -r zap_scan/* reports/
          else
            echo "No zap_scan directory found — skipping copy."
          fi

      - name: Commit ZAP report to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reports/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ZAP scan report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
