name: ZAP Full Scan on Docker Compose App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap-fullscan:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start services with docker-compose.secure.yml
        run: |
          docker-compose -f docker-compose.secure.yml up -d
          echo "Waiting for services to be healthy..."
          sleep 20 # optionally replace with health check

      - name: List running containers
        run: docker ps

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080'
          token: ${{ secrets.GITHUB_TOKEN }} # or use your PAT secret
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          fail_action: false         # don't fail the job even if alerts exist
          allow_issue_writing: false # prevent 403 if you don't need GitHub issues
          cmd_options: '-a -j'
          issue_title: "ZAP Full Scan (docker-compose.secure.yml)"
